name: zaka
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  
  badges: ^1.1.1
  carousel_slider: ^2.3.1
  carousel_pro: ^1.0.0
  states_rebuilder: ^1.14.2
  curved_navigation_bar: ^0.3.2
  flutter_cache_manager: ^1.1.3
  path_provider: ^1.6.1
  path: ^1.6.4
  http: ^0.12.0+4
  intl:
  datetime_picker_formfield: ^1.0.0
  flat_segmented_control: ^0.1.0
  cached_network_image: ^2.0.0
  flutter_custom_dialog: ^1.0.16
  fancy_bottom_navigation: ^0.3.2
 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:     
    - images/BasketNull.png
    - images/juk1.png
    - images/Global.jpg
    - images/Global2.jpg
    - images/Global11.png
    - images/cards.jpg
    - images/LOGO_ZAKA.png
    - images/food.png
    - images/piggy.png
    - images/hand.png
    - images/car.png
    - images/payment.png
    - images/banners/banner1.jpg
    - images/banners/banner2.jpg
    - images/banners/banner3.jpg
    - images/banners/banner4.jpg
    - images/banners/banner5.jpg
    - images/banners/banner6.jpg
    - images/banners/banner7.jpg
    - images/banners/banner8.jpg
    - images/banners/banner9.jpg
    - images/banners/banner10.jpg
    - images/banners/banner11.jpg
    - images/banners/banner12.jpg
    - images/banners/banner13.jpg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

     